name: flutter_paystack
description: A Flutter plugin for making payments via Paystack Payment Gateway. Completely supports Android and iOS.
version: 1.0.9
homepage: https://github.com/codeAvid/flutter_paystack

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  intl: ^0.19.0
  meta: ^1.9.1
  async: ^2.11.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  matcher: ^0.12.15
  mockito: ^5.4.2

flutter:
  plugin:
    platforms:
      android:
        package: co.paystack.flutterpaystack
        pluginClass: FlutterPaystackPlugin
      ios:
        pluginClass: FlutterPaystackPlugin

  assets:
    - assets/images/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"
